spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_booking
spring.datasource.username=hotelbooking
spring.datasource.password=hotelbooking


# Hibernate settings - Use 'create' to create tables from scratch
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Database platform
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Disable spring.jpa.open-in-view warning
spring.jpa.open-in-view=false

# Server port
server.port=8080