# Add these debug logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG
logging.level.com.example.hotelbooking=DEBUG

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_booking
spring.datasource.username=hotelbooking
spring.datasource.password=hotelbooking

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Server
server.port=8080